import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141414ff',
    padding: 8,
    borderRadius: 8,
    position: 'absolute',
    bottom: Platform.select({ ios: 65, android: 75, default: 0 }),
    zIndex: 1000,
    width: '100%',
  },
  infoArea: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cover: { width: 48, height: 48, borderRadius: 4 },
  info: { flex: 1, marginLeft: 12, justifyContent: 'center' },
  title: { fontSize: 14, fontWeight: 'bold', color: '#fff' },
  artist: { fontSize: 12, color: '#b3b3b3' },
  controls: { paddingHorizontal: 8 },
  progressContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    overflow: 'hidden',
  },
  bgBar: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  progressBar: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: '#fff',
    zIndex: 1,
  },
});
