const CATEGORIES = [
  { id: '1', key: 'rock', query: 'rock', color: '#E8115B', image: require('@/assets/images/genres/15.png') },
  { id: '2', key: 'pop', query: 'pop', color: '#1E3264', image: require('@/assets/images/genres/17.png') },
  { id: '3', key: 'hipHop', query: 'hip hop', color: '#BC5900', image: require('@/assets/images/genres/7.webp') },
  { id: '4', key: 'reggaeton', query: 'reggaeton', color: '#E1118C', image: require('@/assets/images/genres/21.avif') },
  { id: '5', key: 'electronic', query: 'electronic', color: '#148A08', image: require('@/assets/images/genres/1.png') },
  { id: '6', key: 'trap', query: 'trap', color: '#AF2896', image: require('@/assets/images/genres/13.png') },
  { id: '7', key: 'rnb', query: 'rnb', color: '#509BF5', image: require('@/assets/images/genres/5.png') },
  { id: '8', key: 'jazz', query: 'jazz', color: '#8D67AB', image: require('@/assets/images/genres/18.png') },
  { id: '9', key: 'blues', query: 'blues', color: '#BA5D07', image: require('@/assets/images/genres/19.png') },
  { id: '10', key: 'country', query: 'country', color: '#777777', image: require('@/assets/images/genres/9.png') },
  { id: '11', key: 'classical', query: 'classical', color: '#B49BC8', image: require('@/assets/images/genres/12.png') },
  { id: '12', key: 'salsa', query: 'salsa', color: '#E13300', image: require('@/assets/images/genres/10.png') },
  { id: '13', key: 'bachata', query: 'bachata', color: '#FF4632', image: require('@/assets/images/genres/8.png') },
  { id: '14', key: 'merengue', query: 'merengue', color: '#C13584', image: require('@/assets/images/genres/11.jpg') },
  { id: '15', key: 'kpop', query: 'k-pop', color: '#1DB954', image: require('@/assets/images/genres/16.png') },
  { id: '16', key: 'metal', query: 'metal', color: '#333333', image: require('@/assets/images/genres/14.png') },
  { id: '17', key: 'punk', query: 'punk', color: '#FF5733', image: require('@/assets/images/genres/6.png') },
  { id: '18', key: 'indie', query: 'indie', color: '#3D91F4', image: require('@/assets/images/genres/3.png') },
  { id: '19', key: 'funk', query: 'funk', color: '#D4AF37', image: require('@/assets/images/genres/4.png') },
  { id: '20', key: 'disco', query: 'disco', color: '#FF9A00', image: require('@/assets/images/genres/20.webp') },
  { id: '21', key: 'house', query: 'house', color: '#00BFFF', image: require('@/assets/images/genres/22.png') },
  { id: '22', key: 'techno', query: 'techno', color: '#0E1A40', image: require('@/assets/images/genres/23.png') },
  { id: '23', key: 'gospel', query: 'gospel', color: '#FFD700', image: require('@/assets/images/genres/24.png') },
  { id: '24', key: 'soul', query: 'soul', color: '#8B0000', image: require('@/assets/images/genres/25.png') },
  { id: '25', key: 'flamenco', query: 'flamenco', color: '#FF4500', image: require('@/assets/images/genres/26.png') },
  { id: '26', key: 'reggae', query: 'reggae', color: '#228B22', image: require('@/assets/images/genres/27.png') },
  { id: '27', key: 'ska', query: 'ska', color: '#2F4F4F', image: require('@/assets/images/genres/28.png') },
  { id: '28', key: 'drill', query: 'drill', color: '#4B0082', image: require('@/assets/images/genres/29.png') },
  { id: '29', key: 'afrobeat', query: 'afrobeat', color: '#DAA520', image: require('@/assets/images/genres/30.png') },
  { id: '30', key: 'lofi', query: 'lo-fi', color: '#6A5ACD', image: require('@/assets/images/genres/2.png') },
] as const;

export default CATEGORIES;
