const CATEGORIES = [
  { id: "1", title: "Rock", color: "#E8115B", image: require("@/assets/images/genres/15.png") },
  { id: "2", title: "Pop", color: "#1E3264", image: require("@/assets/images/genres/17.png") },
  { id: "3", title: "Hip-Hop", color: "#BC5900", image: require("@/assets/images/genres/7.webp") },
  { id: "4", title: "Reggaetón", color: "#E1118C", image: require("@/assets/images/genres/21.avif") },
  { id: "5", title: "Electrónica", color: "#148A08", image: require("@/assets/images/genres/1.png") },
  { id: "6", title: "Trap", color: "#AF2896", image: require("@/assets/images/genres/13.png") },
  { id: "7", title: "R&B", color: "#509BF5", image: require("@/assets/images/genres/5.png") },
  { id: "8", title: "Jazz", color: "#8D67AB", image: require("@/assets/images/genres/18.png") },
  { id: "9", title: "Blues", color: "#BA5D07", image: require("@/assets/images/genres/19.png") },
  { id: "10", title: "Country", color: "#777777", image: require("@/assets/images/genres/9.png") },
  { id: "11", title: "Clásica", color: "#B49BC8", image: require("@/assets/images/genres/12.png") },
  { id: "12", title: "Salsa", color: "#E13300", image: require("@/assets/images/genres/10.png") },
  { id: "13", title: "Bachata", color: "#FF4632", image: require("@/assets/images/genres/8.png") },
  { id: "14", title: "Merengue", color: "#C13584", image: require("@/assets/images/genres/11.jpg") },
  { id: "15", title: "K-Pop", color: "#1DB954", image: require("@/assets/images/genres/16.png") },
  { id: "16", title: "Metal", color: "#333333", image: require("@/assets/images/genres/14.png") },
  { id: "17", title: "Punk", color: "#FF5733", image: require("@/assets/images/genres/6.png") },
  { id: "18", title: "Indie", color: "#3D91F4", image: require("@/assets/images/genres/3.png") },
  { id: "19", title: "Funk", color: "#D4AF37", image: require("@/assets/images/genres/4.png") },
  { id: "20", title: "Disco", color: "#FF9A00", image: require("@/assets/images/genres/20.webp") },
  { id: "21", title: "House", color: "#00BFFF", image: require("@/assets/images/genres/22.png") },
  { id: "22", title: "Techno", color: "#0E1A40", image: require("@/assets/images/genres/23.png") },
  { id: "23", title: "Gospel", color: "#FFD700", image: require("@/assets/images/genres/24.png") },
  { id: "24", title: "Soul", color: "#8B0000", image: require("@/assets/images/genres/25.png") },
  { id: "25", title: "Flamenco", color: "#FF4500", image: require("@/assets/images/genres/26.png") },
  { id: "26", title: "Reggae", color: "#228B22", image: require("@/assets/images/genres/27.png") },
  { id: "27", title: "Ska", color: "#2F4F4F", image: require("@/assets/images/genres/28.png") },
  { id: "28", title: "Drill", color: "#4B0082", image: require("@/assets/images/genres/29.png") },
  { id: "29", title: "Afrobeat", color: "#DAA520", image: require("@/assets/images/genres/30.png") },
  { id: "30", title: "Lo-fi", color: "#6A5ACD", image: require("@/assets/images/genres/2.png") },
];

export default CATEGORIES;
